### ISSUE TITLE
Suppress Emails in bulk edits

### ISSUE THREAD

**Issue by parthchopra** [paginagmbh/redmine_silencer#12]
When I select multiple issues and click edit (Go to the bulk edit page) I don't see the checkbox for suppressing emails. I was wondering if there is a way to do that.
Thanks

**Comment by Atmis** [comment]
I just checked on my installation, and I have the checkbox available to suppress the notification in bulk edit mode.

**Comment by tofi86** [comment]
This should be visible in bulk edit mode. Just checked with 3.3 and 3.4:

![bildschirmfoto 2017-07-26 um 22 17 57](https://user-images.githubusercontent.com/365118/28641669-57cd39be-7250-11e7-9f54-43e723d5e19a.png)

Probably your current role does not have permission to use this feature?

Closing this issue for now. Feel free to reopen if you think something still needs to be fixed.

**Comment by gituser** [comment]
If you have a structure of projects, e.g.

```
Company_Projects
       Project1
              Project33333
       Project2
              Project6666
       Project3
       Project4
```
         
If you try to edit multiple issues from the `Company_Projects` there is no checkbox, otherwise it's there. Maybe you could look and fix.

Thank you.

**Comment by tofi86** [comment]
this issue has been fixed. see #15 for details.
