### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by 11v1** [paginagmbh/redmine_silencer#16]
Hello.

No "supress mail notification" checkbox.
Redmine 3.4.4. Ruby 2.4.3p205 

![default](https://user-images.githubusercontent.com/36913490/39684795-2908cc04-51c7-11e8-8a5d-513a18fa3544.png)
![default](https://user-images.githubusercontent.com/36913490/39684807-34ecdb5a-51c7-11e8-9925-3b01b4241fbe.png)
![default](https://user-images.githubusercontent.com/36913490/39684827-50c50b0e-51c7-11e8-856f-de0e6a17f141.png)

**Comment by gituser** [comment]
you need to select issues in the issue list and right click on them and select 'edit..' and after that there will be a checkbox.
here is an example:
![issue list](https://i.imgur.com/hFtJnyS.png)
and then
![example](https://i.imgur.com/CoV3ioj.png)

**Comment by tofi86** [comment]
@gituser this should also work in a single issue, not only in bulk edit mode.

@11v1 did you add permission to view the checkbox in your/the current role in Admin -> Roles -> `${role}` -> Permissions -> Project ?

**Comment by gituser** [comment]
@tofi86 yes, after your fix there is a checkbox now for a single issue.

**Comment by tofi86** [comment]
@gituser this had been the behaviour ever since!

**Comment by tofi86** [comment]
Closing because Author @gituser doesn't respond anymore.

**Comment by gituser** [comment]
Yes, the issue has been fixed. 
Plugin works as advertised.
Thank you!
