### ISSUE TITLE
Support for Redmine 4

### ISSUE THREAD

**Issue by smap9** [paginagmbh/redmine_silencer#17]
Does this plugin work for redmine 4?

**Comment by tofi86** [comment]
I haven't tested it yet, but I will definately try in the next weeks and make it work with 4.0

Stay tuned! :-)

**Comment by laborb-sb** [comment]
I run the plugin with Redmine 4.0.2.stable without any problems.

**Comment by smap9** [comment]
Hey @tofi86 any news here? 😃

**Comment by tofi86** [comment]
To be honest, I haven't tested yet. But @somnibusse confirmed it works with 4.0.2

Can you give it a try yourself?

**Comment by irasnyd** [comment]
I am also using this plugin (v0.4.3) on redmine 4.0.5 without any problems.

**Comment by tofi86** [comment]
Closing this as it seems to work.
