### ISSUE TITLE
Can't disable email notification when creating issue

### ISSUE THREAD

**Issue by spochiero** [paginagmbh/redmine_silencer#3]
Hi,

Great plugin !

Howhever, we can't disable email notification when creating issue.

**Comment by tofi86** [comment]
Unfortunately, this seems impossible to me.

Even adding the suppress notification button to the "new issue" form was quite tricky as it should appear on new issue form but not on edit issue form. Finally this can be done with:

```ruby
    # render partial when creating new issues BUT NOT when editing issues
    # taken from lib/redmine/hook.rb render_on method
    define_method :view_issues_form_details_bottom do |context|
      # additional condition to render only on action "new" but not on "edit"
      if context[:controller].is_a?(IssuesController) && context[:controller].action_name == "new"
        options = {:partial => 'hooks/silencer_suppress_mail'}
        if context[:hook_caller].respond_to?(:render)
          context[:hook_caller].send(:render, {:locals => context}.merge(options))
        elsif context[:controller].is_a?(ActionController::Base)
          context[:controller].send(:render_to_string, {:locals => context}.merge(options))
        else
          raise "Cannot render #{self.name} hook from #{context[:hook_caller].class.name}"
        end
      end
    end
```

But then, the `Issue` model doesn't have a `notify` field which can be used to suppress notifications and the available controller hooks `:controller_issues_new_before_save` and  `:controller_issues_new_after_save` can't be used either. `:controller_issues_new_after_save` is called after the notification is sent, and `:controller_issues_new_before_save` could be used to tweak the recipients but this would mean deleting the watchers etc. resulting in an incomplete ticket.

Closed as impossible.
